import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    width: '100%',
  },
  title: {
    fontSize: 40,
    color: '#00ff00',
    fontFamily: 'monospace',
    textAlign: 'center',
    marginBottom: 50,
    textShadowColor: '#000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 5,
  },
  button: {
    backgroundColor: '#ff4500',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginVertical: 15,
    borderWidth: 3,
    borderColor: '#ff6347',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    width: '80%',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 24,
    color: '#fff',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  exitButton: {
    backgroundColor: '#d11a2a',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginTop: 30,
    borderWidth: 3,
    borderColor: '#ff4d4d',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    width: '80%',
    alignItems: 'center',
  },
  exitButtonText: {
    fontSize: 24,
    color: '#fff',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
});
