import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4e6c2',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    borderWidth: 1,
    borderColor: '#c8b591',
    width: '100%',
  },
  title: {
    fontSize: 36,
    color: '#5a4632',
    fontFamily: 'serif',
    marginBottom: 30,
    textShadowColor: '#998970',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
  },
  casa: {
    backgroundColor: '#e0d2a4',
    borderWidth: 2,
    borderColor: '#a89b7c',
    padding: 10,
    margin: 5,
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellText: {
    fontSize: 32,
    color: '#5a4632',
    fontFamily: 'serif',
    fontWeight: 'bold',
    textShadowColor: '#998970',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  resetButton: {
    backgroundColor: '#9b8a70',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 5,
    marginVertical: 20,
    borderWidth: 1,
    borderColor: '#705d42',
  },
  exitButton: {
    backgroundColor: '#7c6a53',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#5a4632',
  },
  buttonText: {
    fontSize: 20,
    color: '#fff',
    fontFamily: 'serif',
  },
});
