import { StyleSheet } from 'react-native';

export const styles10 = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0e1a2b',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#004d80',
    width: '100%',
  },
  title: {
    fontSize: 30,
    color: '#66b3ff',
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: '#003366',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 5,
    borderBottomWidth: 2,
    borderBottomColor: '#99ccff',
  },
  resultText: {
    textAlign: 'left',
    width: '83%',
    fontSize: 50,
    color: '#e6f2ff',
    fontFamily: 'Cochin',
    fontWeight: 'bold',
    marginVertical: 30,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    padding: 10,
    backgroundColor: '#1a2a4d',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#b3d1ff',
  },
  rollButton: {
    backgroundColor: '#00509e',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#66a3ff',
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  rollButtonText: {
    fontSize: 22,
    color: '#ffffff',
    fontFamily: 'serif',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  logoutButton: {
    backgroundColor: '#004d66',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#737373',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  logoutButtonText: {
    fontSize: 18,
    color: '#e6f2ff',
    fontFamily: 'serif',
    textTransform: 'uppercase',
  },
});

export const styles20 = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2b0e0e',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#4d2800',
    width: '100%',
  },
  title: {
    fontSize: 30,
    color: '#ffcc00',
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: '#5a3d00',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 5,
    borderBottomWidth: 2,
    borderBottomColor: '#ff9966',
  },
  resultText: {
    textAlign: 'left',
    width: '83%',
    fontSize: 50,
    color: '#f0e6c8',
    fontFamily: 'Cochin',
    fontWeight: 'bold',
    marginVertical: 30,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    padding: 10,
    backgroundColor: '#4c2323',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#b89c73',
  },
  rollButton: {
    backgroundColor: '#6c1f1f',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#b85d19',
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  rollButtonText: {
    fontSize: 22,
    color: '#e5e5e5',
    fontFamily: 'serif',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  logoutButton: {
    backgroundColor: '#663333',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#737373',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  logoutButtonText: {
    fontSize: 18,
    color: '#e5e5e5',
    fontFamily: 'serif',
    textTransform: 'uppercase',
  },
});
