import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1c1c1c',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  title: {
    fontSize: 40,
    color: '#00ff00',
    fontFamily: 'monospace',
    textAlign: 'center',
    marginBottom: 40,
    textShadowColor: '#000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 5,
  },
  input: {
    backgroundColor: '#333333',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#00ff00',
    padding: 15,
    marginVertical: 10,
    fontSize: 18,
    color: '#ffffff',
    fontFamily: 'monospace',
    width: '80%',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#ff4500',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 10,
    marginVertical: 20,
    borderWidth: 2,
    borderColor: '#ff6347',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.7,
    shadowRadius: 5,
  },
  buttonText: {
    fontSize: 22,
    color: '#fff',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
});
