import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#8b4513',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#a0522d',
    width: '100%',
  },
  title: {
    fontSize: 32,
    color: '#fff8dc',
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: '#000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 4,
    borderBottomWidth: 3,
    borderBottomColor: '#d2691e',
  },
  wordDisplay: {
    fontSize: 30,
    color: '#fff8dc',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    letterSpacing: 8,
    marginVertical: 30,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  input: {
    backgroundColor: '#deb887',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#8b4513',
    padding: 10,
    marginVertical: 10,
    fontSize: 20,
    color: '#333',
    fontFamily: 'serif',
    width: '55%',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#6b4226',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#a0522d',
    marginVertical: 15,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    width: '60%',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 20,
    color: '#fff8dc',
    fontFamily: 'serif',
    textTransform: 'uppercase',
    fontWeight: 'bold',
  },
  logoutButton: {
    backgroundColor: '#555555',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginTop: 20,
    borderWidth: 2,
    borderColor: '#333',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    width: '60%',
    alignItems: 'center',
  },
  logoutButtonText: {
    fontSize: 18,
    color: '#fff8dc',
    fontFamily: 'serif',
    textTransform: 'uppercase',
  },
});
